/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ekon;

import java.awt.BorderLayout;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author George
 */
public class MainFrame extends javax.swing.JFrame {

    VytvoreniFirmy vytvorFirmy;
    PanelZalozeniFirmy zalozeniFirmy;
    PanelVypisFirem vypisFirem;
    PanelVypisZamestnancu vypisZamestnancu;
    PanelZalozeniZamestnance zalozeniZamestnance;
    PanelZamestnanecToPDF zalozeniPDF;

    public MainFrame() {
        initComponents();
        setLookAndFeel();
        setSize(850, 750);
        //setExtendedState(MAXIMIZED_BOTH);
        vytvorFirmy = new VytvoreniFirmy();
        zalozeniFirmy = new PanelZalozeniFirmy(vytvorFirmy);
        panelZalozeniFirmy.add(zalozeniFirmy, BorderLayout.CENTER);
        vypisFirem = new PanelVypisFirem(vytvorFirmy);
        panelVypsaniFirem.add(vypisFirem, BorderLayout.CENTER);
        vypisZamestnancu = new PanelVypisZamestnancu(vytvorFirmy);
        panelZamestnancu.add(vypisZamestnancu, BorderLayout.CENTER);
        zalozeniZamestnance = new PanelZalozeniZamestnance(vytvorFirmy);
        panelZalozeniZamestnance.add(zalozeniZamestnance, BorderLayout.CENTER);
        zalozeniPDF = new PanelZamestnanecToPDF(vytvorFirmy);
        panelZamestnanecToPDF.add(zalozeniPDF, BorderLayout.CENTER);
        //pack();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPanelFirma = new javax.swing.JTabbedPane();
        panelZalozeniFirmy = new javax.swing.JPanel();
        panelVypsaniFirem = new javax.swing.JPanel();
        panelZamestnancu = new javax.swing.JPanel();
        panelZalozeniZamestnance = new javax.swing.JPanel();
        panelZamestnanecToPDF = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelZalozeniFirmy.setLayout(new java.awt.BorderLayout());
        tabbedPanelFirma.addTab("Zalozeni Firmy", panelZalozeniFirmy);

        panelVypsaniFirem.setLayout(new java.awt.BorderLayout());
        tabbedPanelFirma.addTab("Vypis Firem ", panelVypsaniFirem);

        panelZamestnancu.setLayout(new java.awt.BorderLayout());
        tabbedPanelFirma.addTab("Editace Firmy", panelZamestnancu);

        panelZalozeniZamestnance.setLayout(new java.awt.BorderLayout());
        tabbedPanelFirma.addTab("ZalozeniZamestnance", panelZalozeniZamestnance);

        panelZamestnanecToPDF.setLayout(new java.awt.BorderLayout());
        tabbedPanelFirma.addTab("Zamestnanec PDF", panelZamestnanecToPDF);

        getContentPane().add(tabbedPanelFirma, java.awt.BorderLayout.PAGE_START);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setLookAndFeel() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (UnsupportedLookAndFeelException ex) {
        }
        SwingUtilities.updateComponentTreeUI(this);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel panelVypsaniFirem;
    private javax.swing.JPanel panelZalozeniFirmy;
    private javax.swing.JPanel panelZalozeniZamestnance;
    private javax.swing.JPanel panelZamestnancu;
    private javax.swing.JPanel panelZamestnanecToPDF;
    private javax.swing.JTabbedPane tabbedPanelFirma;
    // End of variables declaration//GEN-END:variables
}
