/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ekon;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author George
 */
public class PanelZamestnanecToPDF extends javax.swing.JPanel {

    private VytvoreniFirmy vyvtovorFirmy;
    private Firma aktF;
    private Zamestnanec aktZam;
    private zamestnanecToPDF pdf;

    public PanelZamestnanecToPDF(VytvoreniFirmy vytvorFirmy) {
        initComponents();
        this.vyvtovorFirmy = vytvorFirmy;
        this.aktF = null;
        this.aktZam = null;
        this.pdf = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelVyhledaniZamestnance = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFNazevFirmy = new javax.swing.JTextField();
        btnVyhledejFirmu = new javax.swing.JButton();
        textFPrijmeniZamestnance = new javax.swing.JTextField();
        btnVyhledejZamestnance = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblStavNalezenoFirma = new javax.swing.JLabel();
        lblStavNalezenoZamestnanec = new javax.swing.JLabel();
        panelZamestnanecToPDF = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnUlozPDF = new javax.swing.JButton();
        txtFJmeno = new javax.swing.JTextField();
        txtFPrijmeni = new javax.swing.JTextField();
        txtFDatumNarozeni = new javax.swing.JTextField();
        txtFMesto = new javax.swing.JTextField();
        txtFUlice = new javax.swing.JTextField();
        txtFKraj = new javax.swing.JTextField();
        txtFPozice = new javax.swing.JTextField();

        jButton1.setText("Uloz");

        setLayout(new java.awt.BorderLayout());

        panelVyhledaniZamestnance.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Zadejte nazev firmy : ");

        jLabel3.setText("Zadejte přijmení zaměstnance :");

        btnVyhledejFirmu.setText("Vyhledej");
        btnVyhledejFirmu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVyhledejFirmuActionPerformed(evt);
            }
        });

        btnVyhledejZamestnance.setText("Vyhledej ");
        btnVyhledejZamestnance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVyhledejZamestnanceActionPerformed(evt);
            }
        });

        jLabel4.setText("Nalezeno : ");

        jLabel5.setText("Nalezeno : ");

        javax.swing.GroupLayout panelVyhledaniZamestnanceLayout = new javax.swing.GroupLayout(panelVyhledaniZamestnance);
        panelVyhledaniZamestnance.setLayout(panelVyhledaniZamestnanceLayout);
        panelVyhledaniZamestnanceLayout.setHorizontalGroup(
            panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVyhledaniZamestnanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVyhledaniZamestnanceLayout.createSequentialGroup()
                        .addGroup(panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVyhledaniZamestnanceLayout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addComponent(lblStavNalezenoZamestnanec, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelVyhledaniZamestnanceLayout.createSequentialGroup()
                                .addComponent(btnVyhledejZamestnance)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelVyhledaniZamestnanceLayout.createSequentialGroup()
                        .addGroup(panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVyhledaniZamestnanceLayout.createSequentialGroup()
                                .addGroup(panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(btnVyhledejFirmu))
                                .addGroup(panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelVyhledaniZamestnanceLayout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(lblStavNalezenoFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelVyhledaniZamestnanceLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textFNazevFirmy, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelVyhledaniZamestnanceLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(textFPrijmeniZamestnance, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        panelVyhledaniZamestnanceLayout.setVerticalGroup(
            panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVyhledaniZamestnanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelVyhledaniZamestnanceLayout.createSequentialGroup()
                        .addComponent(lblStavNalezenoFirma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textFNazevFirmy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel4)
                        .addGap(7, 7, 7))
                    .addComponent(btnVyhledejFirmu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFPrijmeniZamestnance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelVyhledaniZamestnanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVyhledejZamestnance)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStavNalezenoZamestnanec)
                .addContainerGap())
        );

        add(panelVyhledaniZamestnance, java.awt.BorderLayout.PAGE_START);

        jLabel6.setText("Jmeno :");

        jLabel7.setText("Prijmeni :");

        jLabel8.setText("Datum narozeni :");

        jLabel9.setText("Mesto :");

        jLabel10.setText("Ulice :");

        jLabel11.setText("Kraj :");

        jLabel12.setText("Pozice : ");

        btnUlozPDF.setText("Uloz");
        btnUlozPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUlozPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelZamestnanecToPDFLayout = new javax.swing.GroupLayout(panelZamestnanecToPDF);
        panelZamestnanecToPDF.setLayout(panelZamestnanecToPDFLayout);
        panelZamestnanecToPDFLayout.setHorizontalGroup(
            panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelZamestnanecToPDFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUlozPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelZamestnanecToPDFLayout.createSequentialGroup()
                        .addGroup(panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel6))
                        .addGap(15, 15, 15)
                        .addGroup(panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFKraj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtFUlice, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFMesto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFDatumNarozeni, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFPrijmeni, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFJmeno, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFPozice))))
                .addGap(0, 137, Short.MAX_VALUE))
        );
        panelZamestnanecToPDFLayout.setVerticalGroup(
            panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelZamestnanecToPDFLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFJmeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFPrijmeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFDatumNarozeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFUlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(txtFKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelZamestnanecToPDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtFPozice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUlozPDF)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        add(panelZamestnanecToPDF, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVyhledejFirmuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVyhledejFirmuActionPerformed
        String nazevF = textFNazevFirmy.getText();
        aktF = vyvtovorFirmy.vyhledejFirmu(nazevF);
        if (aktF != null) {
            lblStavNalezenoFirma.setText("Firma nalezena : " + aktF.getNazevFirmy());
        } else {
            lblStavNalezenoFirma.setText("Firma nenalezena !!! : " + nazevF);
        }
    }//GEN-LAST:event_btnVyhledejFirmuActionPerformed

    private void btnVyhledejZamestnanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVyhledejZamestnanceActionPerformed
        String prijmeni = textFPrijmeniZamestnance.getText();
        if (aktF != null) {
            aktZam = aktF.vyhledejZamestnancePodleJmena(prijmeni);
            if (aktZam != null) {
                lblStavNalezenoZamestnanec.setText("Zamestnanec nalezen : " + aktZam.getJmeno() + " " + aktZam.getPrijmeni());
                txtFJmeno.setText(aktZam.getJmeno());
                txtFPrijmeni.setText(aktZam.getPrijmeni());
                txtFDatumNarozeni.setText(aktZam.getDatumNarozeni());
                txtFMesto.setText(aktZam.getMesto());
                txtFUlice.setText(aktZam.getUlice());
                txtFKraj.setText(aktZam.getKraj());
                txtFPozice.setText(aktZam.getPozice());
            } else {
                lblStavNalezenoZamestnanec.setText("Zamestnanec nenalezen !!! : " + prijmeni);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Firma nenalezena", "Chyba", 1);
        }
    }//GEN-LAST:event_btnVyhledejZamestnanceActionPerformed

    private void btnUlozPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUlozPDFActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("objekty pdf", "pdf");
        fc.setFileFilter(filter);
        int resault = fc.showSaveDialog(this);
        if (resault == JFileChooser.APPROVE_OPTION) {
            File fileSelected = fc.getSelectedFile();
            if (aktZam != null) {
                pdf = new zamestnanecToPDF(aktZam);
                pdf.vytvorPDF(fileSelected.getAbsolutePath());
                System.out.println(fileSelected.getAbsoluteFile());
                JOptionPane.showMessageDialog(this, "PDF vytvoreno ", "Informace", 1);
            }
        }
    }//GEN-LAST:event_btnUlozPDFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUlozPDF;
    private javax.swing.JButton btnVyhledejFirmu;
    private javax.swing.JButton btnVyhledejZamestnance;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblStavNalezenoFirma;
    private javax.swing.JLabel lblStavNalezenoZamestnanec;
    private javax.swing.JPanel panelVyhledaniZamestnance;
    private javax.swing.JPanel panelZamestnanecToPDF;
    private javax.swing.JTextField textFNazevFirmy;
    private javax.swing.JTextField textFPrijmeniZamestnance;
    private javax.swing.JTextField txtFDatumNarozeni;
    private javax.swing.JTextField txtFJmeno;
    private javax.swing.JTextField txtFKraj;
    private javax.swing.JTextField txtFMesto;
    private javax.swing.JTextField txtFPozice;
    private javax.swing.JTextField txtFPrijmeni;
    private javax.swing.JTextField txtFUlice;
    // End of variables declaration//GEN-END:variables
}
