/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ekon;

import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author George
 */
public class PanelZalozeniZamestnance extends javax.swing.JPanel {

    VytvoreniFirmy vytvorFirmy;
    Firma aktualniFirma;

    public PanelZalozeniZamestnance(VytvoreniFirmy vytvorFirmy) {
        initComponents();
        this.vytvorFirmy = vytvorFirmy;
        aktualniFirma = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFNazevFirmy = new javax.swing.JTextField();
        btnVyhledejFirmu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblAktualniFirma = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtFJmeno = new javax.swing.JTextField();
        txtFPrijmeni = new javax.swing.JTextField();
        txtFTitul = new javax.swing.JTextField();
        txtFUlice = new javax.swing.JTextField();
        txtFMesto = new javax.swing.JTextField();
        txtFDatumNarozeni = new javax.swing.JTextField();
        comBKraj = new javax.swing.JComboBox();
        txtFRodneCislo = new javax.swing.JTextField();
        txtFEmail = new javax.swing.JTextField();
        txtFTelefon = new javax.swing.JTextField();
        txtFNarodnost = new javax.swing.JTextField();
        comBPozice = new javax.swing.JComboBox();
        btnVlozZamestnance = new javax.swing.JButton();
        btnSmaz = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtFPSC = new javax.swing.JTextField();

        jButton2.setText("jButton2");

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Zadejte nazev firmy : ");

        txtFNazevFirmy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNazevFirmyActionPerformed(evt);
            }
        });

        btnVyhledejFirmu.setText("vyhledej ");
        btnVyhledejFirmu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVyhledejFirmuActionPerformed(evt);
            }
        });

        jLabel2.setText("Aktualni Firma : ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAktualniFirma, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtFNazevFirmy, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVyhledejFirmu)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFNazevFirmy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVyhledejFirmu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblAktualniFirma))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Jméno : ");

        jLabel4.setText("Přimení :");

        jLabel5.setText("Město :");

        jLabel6.setText("Ulice :");

        jLabel7.setText("Kraj :");

        jLabel8.setText("Titul :");

        jLabel9.setText("Datum narození :");

        jLabel10.setText("Rodné číslo :");

        jLabel11.setText("Email :");

        jLabel12.setText("Telefon :");

        jLabel13.setText("Narodnost : ");

        jLabel14.setText("Pozice : ");

        comBKraj.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hlavní město Praha", "Jihočeský kraj", "Jihomoravský kraj", "Karlovarský kraj", "Královehradecký kraj", "Liberecký kraj", "Moravskoslezský kraj", "Olomoucký kraj", "Pardubický kraj", "Plzeňský kraj", "Středočeský kraj", "Ústecký kraj", "Vysočina", "Zlínský kraj" }));

        txtFEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFEmailActionPerformed(evt);
            }
        });

        comBPozice.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zaměstnanec", "Sekretář/ka", "Manažer", "Řiditel" }));

        btnVlozZamestnance.setText("Vloz");
        btnVlozZamestnance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVlozZamestnanceActionPerformed(evt);
            }
        });

        btnSmaz.setText("Smaz");
        btnSmaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSmazActionPerformed(evt);
            }
        });

        jLabel15.setText("PSC :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnVlozZamestnance)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSmaz))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFMesto)
                            .addComponent(txtFPrijmeni)
                            .addComponent(txtFJmeno)
                            .addComponent(txtFTitul)
                            .addComponent(txtFUlice)
                            .addComponent(comBKraj, 0, 160, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFDatumNarozeni)
                            .addComponent(txtFPSC)
                            .addComponent(txtFRodneCislo)
                            .addComponent(txtFEmail)
                            .addComponent(txtFTelefon)
                            .addComponent(txtFNarodnost)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(24, 24, 24)
                        .addComponent(comBPozice, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFJmeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFPrijmeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFTitul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFUlice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comBKraj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtFPSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFDatumNarozeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtFRodneCislo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtFEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtFTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtFNarodnost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(comBPozice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVlozZamestnance)
                    .addComponent(btnSmaz))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFEmailActionPerformed

    private void btnVyhledejFirmuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVyhledejFirmuActionPerformed
        String nazevFirmy = null;
        nazevFirmy = txtFNazevFirmy.getText();
        
        aktualniFirma = vytvorFirmy.vyhledejFirmu(nazevFirmy);
        if(aktualniFirma != null){
        lblAktualniFirma.setText("Firma nalezena");
        }else{
        lblAktualniFirma.setText("Firma nelezena!!!");
        
        }
    }//GEN-LAST:event_btnVyhledejFirmuActionPerformed

    private void btnVlozZamestnanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVlozZamestnanceActionPerformed
        Zamestnanec zam;
        String jmeno;
        String prijmeni;
        String mesto;
        String ulice;
        int psc;
        String kraj;
        String titul;
        String datumNarozeni;
        String email;
        int telefoniCislo;
        int rodneCislo;
        String narodnost;
        String pozice;
        String idZamestnance;
        try {
            jmeno = txtFJmeno.getText();
            prijmeni = txtFPrijmeni.getText();
            mesto = txtFMesto.getText();
            ulice = txtFUlice.getText();
            psc = Integer.valueOf(txtFPSC.getText());
            kraj = comBKraj.getSelectedItem().toString();
            titul = txtFTitul.getText();
            datumNarozeni = txtFDatumNarozeni.getText();
            email = txtFEmail.getText();
            telefoniCislo = Integer.valueOf(txtFTelefon.getText());
            rodneCislo = Integer.valueOf(txtFRodneCislo.getText());
            narodnost = txtFNarodnost.getText();
            pozice = comBPozice.getSelectedItem().toString();

            zam = new Zamestnanec(jmeno, prijmeni, mesto, ulice, psc, kraj, titul, datumNarozeni, email, telefoniCislo, rodneCislo, narodnost, pozice);
            aktualniFirma.pridejZamestnance(zam);
            JOptionPane.showMessageDialog(null, "Zamestnanec pridan", "OK", 1);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "neplatna operace", "Chyba", 0);

        }

    }//GEN-LAST:event_btnVlozZamestnanceActionPerformed

    private void btnSmazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSmazActionPerformed
        txtFDatumNarozeni.setText(null);
        txtFEmail.setText(null);
        txtFJmeno.setText(null);
        txtFMesto.setText(null);
        txtFNarodnost.setText(null);
        txtFNazevFirmy.setText(null);
        txtFPSC.setText(null);
        txtFPrijmeni.setText(null);
        txtFRodneCislo.setText(null);
        txtFTelefon.setText(null);
        txtFTitul.setText(null);
        txtFUlice.setText(null);
    }//GEN-LAST:event_btnSmazActionPerformed

    private void txtFNazevFirmyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNazevFirmyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNazevFirmyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSmaz;
    private javax.swing.JButton btnVlozZamestnance;
    private javax.swing.JButton btnVyhledejFirmu;
    private javax.swing.JComboBox comBKraj;
    private javax.swing.JComboBox comBPozice;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAktualniFirma;
    private javax.swing.JTextField txtFDatumNarozeni;
    private javax.swing.JTextField txtFEmail;
    private javax.swing.JTextField txtFJmeno;
    private javax.swing.JTextField txtFMesto;
    private javax.swing.JTextField txtFNarodnost;
    private javax.swing.JTextField txtFNazevFirmy;
    private javax.swing.JTextField txtFPSC;
    private javax.swing.JTextField txtFPrijmeni;
    private javax.swing.JTextField txtFRodneCislo;
    private javax.swing.JTextField txtFTelefon;
    private javax.swing.JTextField txtFTitul;
    private javax.swing.JTextField txtFUlice;
    // End of variables declaration//GEN-END:variables
}
